# Generated by Django 2.2.3 on 2019-07-11 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('created_at', models.DecimalField(decimal_places=3, max_digits=13)),
                ('session_id', models.TextField(primary_key=True, serialize=False)),
                ('last_renewed', models.DecimalField(decimal_places=3, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('sender_id', models.TextField()),
                ('recipient_id', models.TextField()),
                ('timestamp', models.DecimalField(decimal_places=3, max_digits=13)),
                ('text', models.TextField()),
                ('session', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='watson_bot.Session')),
            ],
        ),
    ]
