# Generated by Django 2.2.3 on 2019-07-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watson_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DecimalField(decimal_places=3, max_digits=13)),
                ('user', models.TextField()),
                ('hobby', models.TextField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='hobby',
            constraint=models.UniqueConstraint(fields=('user', 'hobby'), name='one_of_each_hobby'),
        ),
    ]
