# Generated by Django 2.2.3 on 2019-07-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watson_bot', '0002_auto_20190711_1854'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hobby',
            name='one_of_each_hobby',
        ),
        migrations.RenameField(
            model_name='hobby',
            old_name='hobby',
            new_name='value',
        ),
        migrations.AddConstraint(
            model_name='hobby',
            constraint=models.UniqueConstraint(fields=('user', 'value'), name='one_of_each_hobby'),
        ),
    ]
